//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetFramework_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSimpleValue", ReplyAction="http://tempuri.org/IService/GetSimpleValueResponse")]
        CommonTypes.SomeSharedType GetSimpleValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetSimpleValue", ReplyAction="http://tempuri.org/IService/GetSimpleValueResponse")]
        System.Threading.Tasks.Task<CommonTypes.SomeSharedType> GetSimpleValueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetComplexValue", ReplyAction="http://tempuri.org/IService/GetComplexValueResponse")]
        CommonTypes.AnotherSharedType GetComplexValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetComplexValue", ReplyAction="http://tempuri.org/IService/GetComplexValueResponse")]
        System.Threading.Tasks.Task<CommonTypes.AnotherSharedType> GetComplexValueAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : NetFramework_Client.ServiceReference1.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<NetFramework_Client.ServiceReference1.IService>, NetFramework_Client.ServiceReference1.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CommonTypes.SomeSharedType GetSimpleValue() {
            return base.Channel.GetSimpleValue();
        }
        
        public System.Threading.Tasks.Task<CommonTypes.SomeSharedType> GetSimpleValueAsync() {
            return base.Channel.GetSimpleValueAsync();
        }
        
        public CommonTypes.AnotherSharedType GetComplexValue() {
            return base.Channel.GetComplexValue();
        }
        
        public System.Threading.Tasks.Task<CommonTypes.AnotherSharedType> GetComplexValueAsync() {
            return base.Channel.GetComplexValueAsync();
        }
    }
}
